### ISSUE TITLE
Airports.db is outdated

### ISSUE THREAD

**Issue by cfarrell987** [pbogre/jetlog#50]
The data grabbed from openflights is 5 years old meaning it's missing newer airports such as BER(Berlin Brandenburg Airport). [This list ](https://github.com/davidmegginson/ourairports-data/blob/main/airports.csv) does have up-to-date codes.

**Comment by cfarrell987** [comment]
![image](https://github.com/user-attachments/assets/744ec086-16be-4bee-b3e8-00b2a797bb39)

**Comment by pbogre** [comment]
Thanks for opening the issue, I will look into this shortly :)

**Comment by pbogre** [comment]
I addressed this issue by downloading the data from the provider you mentioned, and adapting it to a format similar to what Jetlog was already using. 

Initially the `airports.csv` database had >50k entries, which is a very large amount and most of it was small airports for non-commercial flights. I decided to strip the database to exclude those airports and some others, because that many airports would have a pretty significant impact on the time taken to load flights and airports.

With this commit, Jetlog with update the `airports` table in `jetlog.db` at every launch, which should make it pretty easy to update the airports database in the future. For future reference, here is the process to adapt the csv files to a database Jetlog can use:

Make sure that you have downloaded `airports.csv`, `countries.csv`, and `regions.csv` from [this repo](https://github.com/davidmegginson/ourairports-data)
```sql
.import --csv airports.csv airports
.import --csv regions.csv regions
.import --csv countries.csv countries
UPDATE airports SET iso_region = (SELECT r.name FROM regions r WHERE r.code = iso_region);
UPDATE airports SET iso_country = (SELECT c.name FROM countries c WHERE c.code = iso_country);
DELETE FROM airports WHERE type = "heliport" OR type = "balloonport";
UPDATE airports SET continent = "Africa" WHERE continent = "AF";
UPDATE airports SET continent = "Antarctica" WHERE continent = "AN";
UPDATE airports SET continent = "Asia" WHERE continent = "AS";
UPDATE airports SET continent = "Europe" WHERE continent = "EU";
UPDATE airports SET continent = "North America" WHERE continent = "NA";
UPDATE airports SET continent = "South America" WHERE continent = "SA";
UPDATE airports SET continent = "Oceania" WHERE continent = "OC";
ALTER TABLE airports DROP COLUMN id;
ALTER TABLE airports DROP COLUMN elevation_ft;
ALTER TABLE airports DROP COLUMN scheduled_service ;
ALTER TABLE airports DROP COLUMN gps_code ;
ALTER TABLE airports DROP COLUMN local_code ;
ALTER TABLE airports DROP COLUMN home_link ;
ALTER TABLE airports DROP COLUMN wikipedia_link ;
ALTER TABLE airports DROP COLUMN keywords ;
DROP TABLE countries;
DROP TABLE regions;
ALTER TABLE airports RENAME COLUMN ident TO icao;
ALTER TABLE airports RENAME COLUMN latitude_deg TO latitude;
ALTER TABLE airports RENAME COLUMN longitude_deg  TO longitude;
ALTER TABLE airports RENAME COLUMN iso_country TO country;
ALTER TABLE airports RENAME COLUMN iso_region TO region;
ALTER TABLE airports RENAME COLUMN iata_code TO iata;
CREATE TABLE _airports (
icao TEXT,
iata TEXT,
type TEXT,
name TEXT,
municipality TEXT,
region TEXT,
country TEXT,
continent TEXT,
latitude FLOAT,
longitude FLOAT);
INSERT INTO _airports (icao, iata, type, name, municipality, region, country, continent, latitude, longitude) SELECT icao, iata, type, name, municipality, region, country, continent, latitude, longitude FROM airports;
DROP TABLE airports;
ALTER TABLE _airports RENAME TO airports;
VACUUM;
```

After the commands above are executed, you will have an sqlite database with *all* airports. For reference, here's how many airports there are for each `type` (after removing those of type `heliport`, of which there are **a lot**):
|`type`|`COUNT(type)`|
|------|-------------|
|closed|11901|
|large_airport|476|
|medium_airport|4710|
|seaplane_base|1189|
|small_airport|41523|

For the commit above, I decided to remove all those with type `small_airport`. Since I noticed that those of type `closed` include large and small airports, I did a bit of a hacky trim but removing all airports with a digit in their icao code. So, here are the commands I used to trim it down to what Jetlog uses now:

```sql
DELETE FROM airports WHERE type = "small_airport"
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%0%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%1%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%2%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%3%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%4%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%5%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%6%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%7%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%8%";
DELETE FROM airports WHERE type = "closed" AND icao LIKE "%9%";
VACUUM;
```

I have not conducted very thorough testing with this new database, so if you wish to test it out you can do so by pulling the `:experimental` image (make sure you export your jetlog data first).

Let me know what you think of this change :)

**Comment by pbogre** [comment]
One downside of the data from ourairports.com is that it does not contain a `city` column, only a `municipality`. This could be the cause of confusion in some cases, however I did what I could to lessen the impact of this change compared to the old database.

**Comment by pbogre** [comment]
With the most recent changes, I finalized the transition into the new airports provider. Feel free to reopen this issue if you encounter any problems regarding this change.
