### ISSUE TITLE
Additional Port Support

### ISSUE THREAD

**Issue by adamzvolanek** [pbogre/jetlog#7]
Would it be possible to allow the container to run on different ports? I have tried to run using the `docker-compose.yaml` file and cannot seem to find a way to run outside of port 3000.

Attempting using

```yaml
    ports:
      - "${SERVER_IP}:8914:8914"
```

or

```yaml
    ports:
      - "${SERVER_IP}:3000:8914"
```

Both times the logs showed the container attempting to running on port 3000.

**Comment by pbogre** [comment]
Thanks for the issue. This was something that I intended to implement  but never got around to. It shouldn't be too hard, I would need to check for the environment variable in `entrypoint.sh` and then use it when serving.

**Comment by pbogre** [comment]
This commit allows you to pick a custom port to expose by specifying the `JETLOG_PORT` environment variable, let me know if this is what you meant.

**Comment by adamzvolanek** [comment]
Ah gotcha! It'd definitely be useful to showcase the different environment variables available for modification on the installation section of the readme. Want me to create a PR?

**Comment by pbogre** [comment]
Yeah it would be useful to have them in the README, especially if I end up putting more in the future. For now they are shown in the `docker-compose.yml`, but if you would like to submit a PR to showcase them in the README that'd be great. It would be nice to have them in a table format like below:

Environment varibles:
|Name|Example|Default|
|----|-------|-------|
|JETLOG_PORT|4100|3000|


I will close this issue since it seems to be resolved
