### ISSUE TITLE
Provide option on Add page to enable faster entry of multiple flights

### ISSUE THREAD

**Issue by bigmak40** [pbogre/jetlog#9]
When doing bulk entry, it would be helpful to have a way to quickly get to the new entry page. 

Two possible ideas:

1. Next to the Done button, put a check box to enable a mode to stay on the page to add more.
2. Add a second button next to Done called something like "Done, add another"

**Comment by pbogre** [comment]
Hi, thanks for the issue. 

I think adding a new button so that it redirects you back to the "New flight" page creates clutter, especially since it's only saving 1 click. Same with adding a checkbox. Would you prefer if after adding a new flight it always redirected you to the "New flight" page instead of the homepage?

Keep in mind that as far as bulk adding goes, I'm planning to add options to import from other services and with custom CSVs, which should make it easier.

**Comment by pbogre** [comment]
Closing this as I am against the idea of adding UI elements to save 1 click, and because the ability to import using a custom CSV mostly fixes this problem anyway.
